# === МОНОХРОМНАЯ ЦВЕТОВАЯ ПАЛИТРА ===

# Основные цвета текста и фона
foreground            #dde1e6
background            #161616
background_opacity    0.85

# Цвет выделения текста и курсора
selection_foreground  #161616
selection_background  #f2f4f8
cursor                #ffffff
cursor_text_color     #161616

# Стандартные цвета терминала (перекрашиваем радугу в монохром)
# Black (Черный и серый)
color0  #262626
color8  #393939

# Red -> Темно-серый
color1  #525252
color9  #6f6f6f

# Green -> Мягкий белый
color2  #e0e0e0
color10 #ffffff

# Yellow -> Светло-серый
color3  #8d8d8d
color11 #a8a8a8

# Blue -> Графитовый
color4  #353535
color12 #4d4d4d

# Magenta -> Пепельный
color5  #616161
color13 #757575

# Cyan -> Серебряный
color6  #a2a2a2
color14 #c1c1c1

# White (Яркий белый)
color7  #f2f4f8
color15 #ffffff
