[main]
# Настраиваем шрифт под стать Waybar и Kitty
font=JetBrainsMono NF:size=14:weight=bold
prompt="❯  "
placeholder="Поиск приложений..."
icon-theme=Papirus-Dark

# Размеры окна лаунчера
width=30
lines=10
tabs=4

# Внутренние отступы, чтобы текст не прижимался к краям
horizontal-pad=20
vertical-pad=15
inner-pad=10

# Радиус закругления углов нашей парящей капсулы
border-radius=12

[colors]
# Формат цветов: RRGGBBAA (последние две цифры — прозрачность)
# background: глубокий чёрный графит с прозрачностью 85% (d9)
background=161616d9
# text: мягкий белый/светло-серый для обычного текста приложений
text=dde1e6ff
# prompt: матовый серый для стрелочки поиска
prompt=878d96ff
# placeholder: тёмно-серый для текста подсказки
placeholder=525861ff
# input: чисто-белый для текста, который вы вбиваете руками
input=ffffffff

# Настройки выделенной (активной) строки
# selection: благородный тёмно-серый фон для выбранного пункта с прозрачностью 90% (e6)
selection=343a40e6
# selection-text: ультра-белый цвет текста для выделенного приложения
selection-text=ffffffff

# Настройка рамки вокруг всего окна лаунчера (тонкая белая линия с 10% прозрачности)
border=ffffff1a

[border]
width=1
radius=12
